services:
  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: always
    environment:
      - PUID=1000
      - PGID=100
      - UMASK=002
      - TZ=Australia/Adelaide
    volumes:
      - /home/braden/prowlarr:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: container:gluetun
