---
services:
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=100
      - UMASK=002
      - TZ=Australia/Adelaide
    volumes:
      - ~/prowlarr:/config:rw
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: container:gluetun
