---
services:
  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=100
      - UMASK=002
      - TZ=Australia/Adelaide
    volumes:
      - ~/bazarr:/config:rw
      - /srv/dev-disk-by-uuid-6e489cc6-dacc-48eb-a977-d75413376e50/media:/data:rw
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: container:gluetun
