services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 9091:9091 # qbit web
      - 6767:6767 # bazarr
      - 7878:7878 # radarr
      - 8989:8989 # sonarr
      - 9696:9696 # prowlarr
    volumes:
      - /home/braden/gluetun:/gluetun
    environment:
      - PUID=1000
      - PGID=100
      - UMASK=002
      - TZ=Australia/Adelaide

networks:
  default:
    name: vpn
    external: true
